public_ip: 192.168.132.30
password: admin@123
user_name : administrator@ytdev.com
domain_name: ytdev.com

admin_password: admin@123 #For VNC viewer for MFA
ad_admin_password: admin@123 #for MFA
ad_user: aduser #for MFA
ad_password: admin@123 #for MFA
