public_ip: 192.168.23.104
root_password: bhpssword
normal_password: C0mm0nPa$$w0rd
super_password:  C0mm0nPa$$w0rd
locu01_password: C0mm0nPa$$w0rd
blocal1_password: C0mm0nPa$$w0rd
blocal2_password: C0mm0nPa$$w0rd
blocal3_password: C0mm0nPa$$w0rd
blocal5_password: C0mm0nPa$$w0rd
blocal6_password: C0mm0nPa$$w0rd

